# Generated by Django 5.1.3 on 2024-11-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
    ]
