# Generated by Django 5.1.3 on 2024-11-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_seat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='seat',
            name='showtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.showtime'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('showtime', 'seat_number')},
        ),
    ]
