# Generated by Django 5.1.3 on 2024-11-30 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_seat_options_seat_showtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='showtime',
            field=models.ForeignKey(db_column='showtime_id', on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.showtime'),
        ),
    ]
