# Generated by Django 5.1.3 on 2024-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff')], max_length=8)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('staff_role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Staff', 'Staff')], max_length=7, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
